# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink: "/:categories/:title.html"

# Setup
title:            Pagidimarri Nagendar
tagline:          'A Jekyll theme'
description:      'Experienced Software Engineer specializing in building scalable systems | B.Tech in Computer Science'
url:              https://nagendar-pm.github.io
baseurl:          /

author:
  name:           'Pagidimarri Nagendar'
  url:            https://www.linkedin.com/in/nagendar-pagidimarri/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/nagendar-pm/

resume:
  link:           https://drive.google.com/file/d/1ohazSkP5i3Exq7DTqtlyq1BYgO9JVRjI/view?usp=sharing

excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-figure

jekyll-figure:
  paragraphs: false

# pagination:
#   enabled: true
#   per_page: 5
#   title: ':title - page :num'
#   sort_field: 'date'
#   sort_reverse: true
#   trail:
#     before: 2
#     after: 2
#   categories:
#     projects:
#       path: '/projects/page/:num/'
#       paginate_path: '/projects/page/:num/'
#       layout: category
#       category: projects

# paginate_path: "/projects/page:num/"