# Dependencies
markdown:         redcarpet
highlighter:      pygments

# # Permalinks
# permalink:        pretty
# relative_permalinks: true

# Permalinks
permalink: "/:title.html"

# Setup
title:            Pagidimarri Nagendar
tagline:          'A Jekyll theme'
description:      'Experienced Software Engineer Specializing in building Scalable Systems | B.Tech in Computer Science'
url:              https://nagendar-pm.github.io
baseurl:          /

author:
  name:           'Pagidimarri Nagendar'
  url:            https://www.linkedin.com/in/nagendar-pagidimarri/

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/nagendar-pm/

resume:
  link:           https://drive.google.com/file/d/1yAjysYibu5_TYz_1J8LNBk3EYWgc4D0T/view?usp=drive_link

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
